set(LLVM_MINGW_PATH "/opt/llvm-mingw")
set(LLVM_MINGW_TARGET_PLATFORM_PREFIX "aarch64")
set(LLVM_MINGW_PREFIX "${LLVM_MINGW_TARGET_PLATFORM_PREFIX}-w64-mingw32")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR "${LLVM_MINGW_TARGET_PLATFORM_PREFIX}")
set(CMAKE_C_COMPILER "${LLVM_MINGW_PATH}/bin/${LLVM_MINGW_PREFIX}-clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_PATH}/bin/${LLVM_MINGW_PREFIX}-clang++")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_PATH}/bin/${LLVM_MINGW_PREFIX}-windres")
set(CMAKE_LINKER "${LLVM_MINGW_PATH}/bin/ld.lld")

set(CMAKE_C_FLAGS "--target=${LLVM_MINGW_PREFIX}")
set(CMAKE_CXX_FLAGS "--target=${LLVM_MINGW_PREFIX}")
set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}")
set(CMAKE_SYSROOT "${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}")

# Configure linker flags
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld -L${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}/lib -static -static-libstdc++ -static-libgcc")
set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld -L${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}/lib -static -static-libstdc++ -static-libgcc")
set(CMAKE_MODULE_LINKER_FLAGS "-fuse-ld=lld -L${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}/lib -static -static-libstdc++ -static-libgcc")

# Search settings
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)